name: "Coverage Report for lcov format"
description: "Comments a pull request with code coverage"
author: "GY Noh"
branding:
  icon: "check-square"
  color: "green"
inputs:
  github-token:
    description: "secrets.GITHUB_TOKEN"
    required: true
  simplecov-json-path:
    description: "Relative path of coverage/coverage.json"
    required: false
    default: 'coverage/coverage.json'
runs:
  using: "node12"
  main: "dist/index.js"
